-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.12.1.454
-- Module  Version: 5.7
-- Sat Sep 09 16:17:18 2023

-- parameterized module component declaration
component PLL200
    port (CLKI: in  std_logic; CLKOP: out  std_logic);
end component;

-- parameterized module component instance
__ : PLL200
    port map (CLKI=>__, CLKOP=>__);
