-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.13.0.56.2
-- Module  Version: 5.7
-- Sat Nov 09 17:08:41 2024

-- parameterized module component declaration
component PLL_56_81
    port (CLKI: in  std_logic; CLKOP: out  std_logic; 
        CLKOS: out  std_logic);
end component;

-- parameterized module component instance
__ : PLL_56_81
    port map (CLKI=>__, CLKOP=>__, CLKOS=>__);
