-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.13.0.56.2
-- Module  Version: 5.7
-- Sat Nov 09 19:25:26 2024

-- parameterized module component declaration
component PLL_56_94
    port (CLKI: in  std_logic; CLKOP: out  std_logic; 
        CLKOS: out  std_logic);
end component;

-- parameterized module component instance
__ : PLL_56_94
    port map (CLKI=>__, CLKOP=>__, CLKOS=>__);
