-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.13.0.56.2
-- Module  Version: 5.7
-- Tue Nov 19 23:41:16 2024

-- parameterized module component declaration
component PLL_57
    port (CLKI: in  std_logic; CLKOP: out  std_logic; 
        CLKOS: out  std_logic);
end component;

-- parameterized module component instance
__ : PLL_57
    port map (CLKI=>__, CLKOP=>__, CLKOS=>__);
