-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.14.0.75.2
-- Module  Version: 5.7
-- Tue Nov 04 10:43:19 2025

-- parameterized module component declaration
component PLL_14
    port (CLKI: in  std_logic; CLKOP: out  std_logic; 
        CLKOS: out  std_logic);
end component;

-- parameterized module component instance
__ : PLL_14
    port map (CLKI=>__, CLKOP=>__, CLKOS=>__);
