-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.14.0.75.2
-- Module  Version: 5.7
-- Thu Oct 23 11:35:56 2025

-- parameterized module component declaration
component PLL_28
    port (CLKI: in  std_logic; CLKOP: out  std_logic; 
        CLKOS: out  std_logic);
end component;

-- parameterized module component instance
__ : PLL_28
    port map (CLKI=>__, CLKOP=>__, CLKOS=>__);
