-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.13.0.56.2
-- Module  Version: 5.7
-- Fri Aug 08 17:27:42 2025

-- parameterized module component declaration
component PLL_48
    port (CLKI: in  std_logic; CLKOP: out  std_logic; 
        CLKOS: out  std_logic; CLKOS2: out  std_logic);
end component;

-- parameterized module component instance
__ : PLL_48
    port map (CLKI=>__, CLKOP=>__, CLKOS=>__, CLKOS2=>__);
