-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.12.1.454
-- Module  Version: 5.7
-- Fri Jun 30 15:31:07 2023

-- parameterized module component declaration
component PLL_21_375
    port (CLKI: in  std_logic; CLKOP: out  std_logic);
end component;

-- parameterized module component instance
__ : PLL_21_375
    port map (CLKI=>__, CLKOP=>__);
