-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.13.0.56.2
-- Module  Version: 5.7
-- Mon Aug 12 16:18:30 2024

-- parameterized module component declaration
component PLL_24
    port (CLKI: in  std_logic; PLLCLK: in  std_logic; 
        PLLRST: in  std_logic; PLLSTB: in  std_logic; 
        PLLWE: in  std_logic; PLLDATI: in  std_logic_vector(7 downto 0); 
        PLLADDR: in  std_logic_vector(4 downto 0); CLKOP: out  std_logic; 
        CLKOS: out  std_logic; 
        PLLDATO: out  std_logic_vector(7 downto 0); 
        PLLACK: out  std_logic);
end component;

-- parameterized module component instance
__ : PLL_24
    port map (CLKI=>__, PLLCLK=>__, PLLRST=>__, PLLSTB=>__, PLLWE=>__, 
        PLLDATI(7 downto 0)=>__, PLLADDR(4 downto 0)=>__, CLKOP=>__, 
        CLKOS=>__, PLLDATO(7 downto 0)=>__, PLLACK=>__);
