-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.14.0.75.2
-- Module  Version: 5.4
-- Sun Feb 01 12:03:32 2026

-- parameterized module component declaration
component TITLES
    port (Address: in  std_logic_vector(7 downto 0); 
        OutClock: in  std_logic; OutClockEn: in  std_logic; 
        Reset: in  std_logic; Q: out  std_logic_vector(95 downto 0));
end component;

-- parameterized module component instance
__ : TITLES
    port map (Address(7 downto 0)=>__, OutClock=>__, OutClockEn=>__, 
        Reset=>__, Q(95 downto 0)=>__);
