-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.12.1.454
-- Module  Version: 5.7
-- Wed Sep 20 11:46:52 2023

-- parameterized module component declaration
component PLL28_6
    port (CLKI: in  std_logic; CLKOP: out  std_logic; 
        CLKOS: out  std_logic);
end component;

-- parameterized module component instance
__ : PLL28_6
    port map (CLKI=>__, CLKOP=>__, CLKOS=>__);
